version: '3.8'

services:
  # MongoDB para AccessMicroservice
  mongodb-access:
    image: mongo:latest
    container_name: mongodb-access
    ports:
      - "27018:27017"
    volumes:
      - mongodb-access-data:/data/db

  # RabbitMQ para AccessMicroservice
  rabbitmq-access:
    image: rabbitmq:3-management
    container_name: rabbitmq-access
    ports:
      - "5673:5672"
      - "15673:15672"  # Interfaz de administración
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  # MongoDB para CareersMicroservice
  mongodb-careers:
    image: mongo:latest
    container_name: mongodb-careers
    ports:
      - "27017:27017"
    volumes:
      - mongodb-careers-data:/data/db

  # RabbitMQ para CareersMicroservice
  rabbitmq-careers:
    image: rabbitmq:3-management
    container_name: rabbitmq-careers
    ports:
      - "5672:5672"
      - "15672:15672"  # Interfaz de administración
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

volumes:
  mongodb-access-data:
  mongodb-careers-data:
